# Generated by Django 5.1.1 on 2025-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0002_parentsforum_model_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guides_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=100)),
                ("desc", models.TextField(max_length=2000)),
                (
                    "image_url",
                    models.CharField(
                        default="images/others/default.jpg", max_length=200
                    ),
                ),
                (
                    "guide_type",
                    models.CharField(
                        choices=[
                            ("parent", "Parent Guide"),
                            ("nutrition", "Nutrition Guide"),
                        ],
                        default="parent",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NutritionGuides_Model",
        ),
        migrations.DeleteModel(
            name="ParentsGuides_Model",
        ),
        migrations.CreateModel(
            name="NutritionGuides_Model",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tinySteps.guides_model",),
        ),
        migrations.CreateModel(
            name="ParentsGuides_Model",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tinySteps.guides_model",),
        ),
    ]
