# Generated by Django 5.1.1 on 2025-03-16 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0002_calendarevent_model_guides_model_like_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalArticle_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "source_name",
                    models.CharField(max_length=100, verbose_name="Source Name"),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Author"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="Image URL"),
                ),
                ("published_at", models.DateTimeField(verbose_name="Published At")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("parenting", "Parenting"),
                            ("nutrition", "Nutrition"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Content"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "External Article",
                "verbose_name_plural": "External Articles",
                "ordering": ["-published_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="calendarevent_model",
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
            },
        ),
        migrations.AlterModelOptions(
            name="comment_model",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="guides_model",
            options={"verbose_name": "Guide", "verbose_name_plural": "Guides"},
        ),
        migrations.AlterModelOptions(
            name="milestone_model",
            options={"verbose_name": "Milestone", "verbose_name_plural": "Milestones"},
        ),
        migrations.AlterModelOptions(
            name="notification_model",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="nutritionguides_model",
            options={
                "verbose_name": "Nutrition Guide",
                "verbose_name_plural": "Nutrition Guides",
            },
        ),
        migrations.AlterModelOptions(
            name="parentsforum_model",
            options={
                "verbose_name": "Parents Forum Post",
                "verbose_name_plural": "Parents Forum Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="parentsguides_model",
            options={
                "verbose_name": "Parent Guide",
                "verbose_name_plural": "Parent Guides",
            },
        ),
        migrations.AlterModelOptions(
            name="passwordreset_model",
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="vaccine_model",
            options={"verbose_name": "Vaccine", "verbose_name_plural": "Vaccines"},
        ),
        migrations.AlterModelOptions(
            name="vaccinecard_model",
            options={
                "verbose_name": "Vaccine Card",
                "verbose_name_plural": "Vaccine Cards",
            },
        ),
        migrations.AlterModelOptions(
            name="yourchild_model",
            options={"verbose_name": "Child", "verbose_name_plural": "Children"},
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="tinySteps.yourchild_model",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="has_reminder",
            field=models.BooleanField(default=False, verbose_name="Has reminder"),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="reminder_minutes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Reminder minutes"
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="type",
            field=models.CharField(
                choices=[
                    ("doctor", "Medical Appointment"),
                    ("vaccine", "Vaccine"),
                    ("milestone", "Development Milestone"),
                    ("feeding", "Feeding"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="comment_model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="comment_model",
            name="text",
            field=models.TextField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="contact_model",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="contact_model",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contact_model",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contact_model",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="desc",
            field=models.TextField(max_length=2000, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="guide_type",
            field=models.CharField(
                choices=[("parent", "Parent Guide"), ("nutrition", "Nutrition Guide")],
                default="parent",
                max_length=20,
                verbose_name="Guide type",
            ),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="image_url",
            field=models.CharField(
                default="images/others/default.jpg",
                max_length=200,
                verbose_name="Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="like_model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="milestone_model",
            name="achieved_date",
            field=models.DateField(verbose_name="Achieved date"),
        ),
        migrations.AlterField(
            model_name="milestone_model",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="milestone_model",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="milestone_photos/",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="milestone_model",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="notification_model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="notification_model",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="notification_model",
            name="read",
            field=models.BooleanField(default=False, verbose_name="Read"),
        ),
        migrations.AlterField(
            model_name="parentsforum_model",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="parentsforum_model",
            name="desc",
            field=models.TextField(max_length=2000, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="parentsforum_model",
            name="title",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="passwordreset_model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="passwordreset_model",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="Is used"),
        ),
        migrations.AlterField(
            model_name="vaccine_model",
            name="administered",
            field=models.BooleanField(default=False, verbose_name="Administered"),
        ),
        migrations.AlterField(
            model_name="vaccine_model",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="vaccine_model",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="vaccine_model",
            name="next_dose_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next dose date"
            ),
        ),
        migrations.AlterField(
            model_name="vaccine_model",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="age",
            field=models.IntegerField(verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="birth_date",
            field=models.DateField(verbose_name="Birth date"),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="desc",
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="Height"),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="child_photos/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="Image URL"),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="second_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Second name"
            ),
        ),
        migrations.AlterField(
            model_name="yourchild_model",
            name="weight",
            field=models.FloatField(blank=True, null=True, verbose_name="Weight"),
        ),
        migrations.CreateModel(
            name="ExternalNutritionData_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient",
                    models.CharField(max_length=200, verbose_name="Ingredient"),
                ),
                ("data", models.JSONField(verbose_name="Nutrition Data")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "External Nutrition Data",
                "verbose_name_plural": "External Nutrition Data",
                "unique_together": {("ingredient",)},
            },
        ),
    ]
