# Generated by Django 5.1.1 on 2025-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0003_externalarticle_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalarticle_model",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
