# Generated by Django 5.1.1 on 2025-03-23 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0006_profile_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guides_model",
            options={},
        ),
        migrations.AddField(
            model_name="guides_model",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved at"
            ),
        ),
        migrations.AddField(
            model_name="guides_model",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set this field when the guide is published.",
                null=True,
                verbose_name="Published at",
            ),
        ),
        migrations.AddField(
            model_name="guides_model",
            name="rejection_reason",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Rejection Reason"
            ),
        ),
        migrations.AddField(
            model_name="guides_model",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO-friendly URL; auto-generated if empty.",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AddField(
            model_name="guides_model",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
