# Generated by Django 5.1.1 on 2025-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tinySteps",
            "0007_alter_guides_model_options_guides_model_approved_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parentsforum_model",
            name="category",
            field=models.CharField(
                choices=[
                    ("feeding", "Feeding"),
                    ("sleep", "Sleep"),
                    ("development", "Development"),
                    ("health", "Health"),
                    ("behavior", "Behavior"),
                    ("travel", "Travel"),
                    ("safety", "Safety"),
                    ("family", "Family"),
                    ("care", "Baby Care"),
                    ("celebration", "Celebrations"),
                    ("food", "Food"),
                    ("advice", "Advice"),
                ],
                default="advice",
                max_length=20,
                verbose_name="Category",
            ),
        ),
    ]
