# Generated by Django 5.1.1 on 2025-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0008_parentsforum_model_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guides_model",
            name="image_url",
        ),
        migrations.AddField(
            model_name="guides_model",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for the guide.",
                null=True,
                upload_to="guide_images/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="parentsforum_model",
            name="category",
            field=models.CharField(
                choices=[
                    ("advice", "Advice"),
                    ("feeding", "Feeding"),
                    ("sleep", "Sleep"),
                    ("health", "Health"),
                    ("development", "Development"),
                    ("care", "Baby Care"),
                ],
                default="advice",
                max_length=20,
                verbose_name="Category",
            ),
        ),
    ]
