# Generated by Django 5.1.1 on 2025-03-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0009_remove_guides_model_image_url_guides_model_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guides_model",
            name="tags",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated tags for the guide.",
                null=True,
                verbose_name="Tags",
            ),
        ),
    ]
