# Generated by Django 5.1.1 on 2025-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0010_guides_model_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionerror_model",
            name="client_ip",
            field=models.GenericIPAddressField(default="0.0.0.0"),
        ),
        migrations.AlterField(
            model_name="connectionerror_model",
            name="error_type",
            field=models.CharField(
                choices=[
                    ("broken_pipe", "Broken Pipe"),
                    ("connection_reset", "Connection Reset"),
                    ("timeout", "Timeout"),
                    ("internal_server", "Internal Server Error"),
                    ("other", "Other Error"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="connectionerror_model",
            name="traceback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="connectionerror_model",
            name="user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="connectionerror_model",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
