# Generated by Django 5.1.1 on 2025-03-30 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0012_category_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="guides_model",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="tinySteps.category_model",
                verbose_name="Category",
            ),
        ),
    ]
