# Generated by Django 5.1.1 on 2025-03-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0013_guides_model_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent_model",
            options={
                "ordering": ["date", "time"],
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
            },
        ),
        migrations.AddField(
            model_name="calendarevent_model",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
    ]
