# Generated by Django 5.1.1 on 2025-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0014_alter_calendarevent_model_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent_model",
            name="is_all_day",
            field=models.BooleanField(default=False, verbose_name="All day event"),
        ),
        migrations.AddField(
            model_name="calendarevent_model",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Reminder sent"),
        ),
        migrations.AddField(
            model_name="calendarevent_model",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent_model",
            name="type",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor Appointment"),
                    ("vaccine", "Vaccine"),
                    ("milestone", "Development Milestone"),
                    ("feeding", "Feeding"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent_model",
            index=models.Index(
                fields=["child", "date"], name="tinySteps_c_child_i_93f6ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent_model",
            index=models.Index(fields=["type"], name="tinySteps_c_type_a3a605_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarevent_model",
            index=models.Index(fields=["status"], name="tinySteps_c_status_71fb8d_idx"),
        ),
    ]
