# Generated by Django 5.1.1 on 2025-05-14 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0015_calendarevent_model_is_all_day_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guides_model",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_moderate_guide", "Can moderate guides")],
                "verbose_name": "Guide",
                "verbose_name_plural": "Guides",
            },
        ),
        migrations.AddField(
            model_name="guides_model",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_guides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guides_model",
            name="moderation_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Moderation Date"
            ),
        ),
        migrations.AddField(
            model_name="guides_model",
            name="moderation_notes",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Moderation Notes"
            ),
        ),
        migrations.AddField(
            model_name="guides_model",
            name="summary",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Summary"
            ),
        ),
        migrations.AddField(
            model_name="guides_model",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published at"
            ),
        ),
        migrations.AddIndex(
            model_name="guides_model",
            index=models.Index(fields=["status"], name="tinySteps_g_status_c7adf1_idx"),
        ),
        migrations.AddIndex(
            model_name="guides_model",
            index=models.Index(
                fields=["guide_type"], name="tinySteps_g_guide_t_bd1220_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guides_model",
            index=models.Index(
                fields=["author"], name="tinySteps_g_author__de12e6_idx"
            ),
        ),
    ]
